[package]
name = "My-ToDo_CLI"
version = "0.0.1"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
uuid = { version = "1.0", features = ["v4"] }
clap = { version = "4.5.32", features = ["derive"] }
dirs-next = "2.0.0"
